name: build image and push to docker registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
            
      - run: mvn clean install docker:build
      - name: Tag Docker image
        run: |
          REPO_NAME=$(basename $(pwd))
          docker tag dnyanyog.org/$REPO_NAME:latest ${{secrets.DOCKER_REGISTRY_USER}}/$REPO_NAME:$GITHUB_REF_NAME
          docker images          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GH_TOKEN }} 
      - name: Push Docker image to GitHub Packages
        run: |
          REPO_NAME=$(basename $(pwd))
          docker push ${{ secrets.DOCKER_REGISTRY_USER }}/$REPO_NAME:$GITHUB_REF_NAME