name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Google Java Formatter Check
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.